/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GMP */

#ifndef _Included_GMP
#define _Included_GMP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GMP
 * Method:    natInitializeLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GMP_natInitializeLibrary
  (JNIEnv *, jclass);

/*
 * Class:     GMP
 * Method:    natInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GMP_natInitialize
  (JNIEnv *, jobject);

/*
 * Class:     GMP
 * Method:    natFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GMP_natFinalize
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
