/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class GMP */

#ifndef _Included_GMP
#define _Included_GMP
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     GMP
 * Method:    natInitializeLibrary
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GMP_natInitializeLibrary
  (JNIEnv *, jclass);

/*
 * Class:     GMP
 * Method:    natInitialize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GMP_natInitialize
  (JNIEnv *, jobject);

/*
 * Class:     GMP
 * Method:    natFinalize
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_GMP_natFinalize
  (JNIEnv *, jobject);

/*
 * Class:     GMP
 * Method:    natFromLong
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_GMP_natFromLong
  (JNIEnv *, jobject, jlong);

/*
 * Class:     GMP
 * Method:    natFromString
 * Signature: (Ljava/lang/String;I)I
 */
JNIEXPORT jint JNICALL Java_GMP_natFromString
  (JNIEnv *, jobject, jstring, jint);

/*
 * Class:     GMP
 * Method:    natToString
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_GMP_natToString
  (JNIEnv *, jobject, jint);

/*
 * Class:     GMP
 * Method:    natDoubleValue
 * Signature: ()D
 */
JNIEXPORT jdouble JNICALL Java_GMP_natDoubleValue
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
